export const stores = `CREATE TABLE IF NOT EXISTS public.Stores (
    id BIGSERIAL PRIMARY KEY,
    uuid TEXT UNIQUE NOT NULL,
    store_name TEXT,
    store_domain TEXT UNIQUE NOT NULL,
    store_email TEXT,
    shopify_access_token TEXT UNIQUE NOT NULL,
    plan_name VARCHAR(100) DEFAULT NULL,
    is_free_planned BOOLEAN DEFAULT FALSE,
    is_installed BOOLEAN,
    trail_started BOOLEAN,
    is_first_time BOOLEAN,
    payment_status TEXT,
    trail_expires_on DATE,
    charge_id BIGINT,    
    webhooks_registered BOOLEAN,
    feature_check BOOLEAN DEFAULT FALSE,
    stage_one_time BOOLEAN DEFAULT FALSE,
    review_form_one_time BOOLEAN DEFAULT FALSE,
    review_proofing_one_time BOOLEAN DEFAULT FALSE,
    review_wall_one_time BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;