# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d9fb0074152e9f75b4e81672c29a0a2"
application_url = "https://happening-attached-ballot-consent.trycloudflare.com"
embedded = true
name = "reviewSuiteApp"
handle = "reviewsuiteapp"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tespapp.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://happening-attached-ballot-consent.trycloudflare.com/auth/callback",
  "https://happening-attached-ballot-consent.trycloudflare.com/auth/shopify/callback",
  "https://happening-attached-ballot-consent.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
